### ISSUE TITLE
TypeError: 'threadsafe_iter' object is not an iterator

### ISSUE THREAD

**Issue by primasanjaya** [lalonderodney/SegCaps#14] opened 2018-10-12 03:32 UTC
why the threadsafe_iter class for training and validation generator are not iterator?

**Comment by avassadi** [comment] 2018-12-02 22:57
I have the same issue. @primasanjaya did you find any solution?

**Comment by primasanjaya** [comment] 2018-12-06 08:04
> I have the same issue. @primasanjaya did you find any solution?
i use this repo
https://github.com/Cheng-Lin-Li/SegCaps

**Comment by lalonderodney** [comment] 2018-12-06 08:31
Hello @primasanjaya and @avassadi,

I'm sorry you're having an issue. I have no problems running the code on my end. You can try removing the function threadsafe_generator and remove all of the @threadsafe_generator's and see if this helps, although then your generators won't be threadsafe :)

**Comment by WonderSeven** [comment] 2019-01-21 03:44
Hi, @lalonderodney 
I just meet the same qusetion, and if i remove @threadsafe_generator's the the code still be broken down, the infos like "Keras requires a thread-safe generator...". It seems like a contradiction.

**Comment by lalonderodney** [comment] 2019-01-21 03:55
Hmmm odd. Are you running the newest versions of Keras and Tensorflow? I am not able to reproduce this error. Has anyone else solved this issue the few of you seem to be having? @primasanjaya, @avassadi, @WonderSeven. Maybe try checking out this repo (https://github.com/Cheng-Lin-Li/SegCaps) or ask the author there if you are unable to solve. If all else fails I will need more details to first reproduce the error in order to help.

**Comment by WonderSeven** [comment] 2019-01-21 05:03
Thanks for your suggestions. My environment is 
python 3.6
Keras-gpu 2.24
tensorflow-gpu 1.11.0
And i use your repo now, so i shall to try the newest version as you suggested. Hope it will work well.

**Comment by lalonderodney** [comment] 2019-01-21 05:14
Interesting, perhaps it is a python 2 vs 3 issue. I run everything in Python 2. That's the most likely culprit right now I'm betting.

**Comment by WonderSeven** [comment] 2019-01-21 08:22
Yeah，you did a right  inferance！
The issue could be fixed by replacing the next() in threadsafe_iter to \_\_next\_\_. This is the difference between py2 and py3. And in new version as [https://github.com/Cheng-Lin-Li/SegCaps](https://github.com/Cheng-Lin-Li/SegCaps/blob/master/utils/threadsafe.py)，this has been updated.

**Comment by lalonderodney** [comment] 2019-02-15 09:09
Thank you very much for your help. If I ever get some of the countless projects/papers off my plate and can get around to updating this repo I will surely add this to the list. In the meantime I appreciate very much (https://github.com/Cheng-Lin-Li/SegCaps) for keeping his repo better up to date.

**Closed as completed by lalonderodney** 2019-02-15 09:09 UTC

**Comment by sindhura234** [comment] 2021-11-21 21:05
How to use the utils.datasafe.py updation ?
I too got this error. Please help me fix it 
`  history = model.fit_generator(
Traceback (most recent call last):
  File "/mnt/DATA/sindhura/SegCaps/main.py", line 175, in <module>
    main(arguments)
  File "/mnt/DATA/sindhura/SegCaps/main.py", line 82, in main
    train(args, train_list, val_list, model_list[0], net_input_shape)
  File "/mnt/DATA/sindhura/SegCaps/train.py", line 139, in train
    history = model.fit_generator(
  File "/mnt/DATA/anaconda3/envs/segcaps/lib/python3.9/site-packages/keras/engine/training.py", line 2016, in fit_generator
    return self.fit(
  File "/mnt/DATA/anaconda3/envs/segcaps/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/mnt/DATA/anaconda3/envs/segcaps/lib/python3.9/site-packages/keras/engine/data_adapter.py", line 863, in _peek_and_restore
    peek = next(x)
TypeError: 'threadsafe_iter' object is not an iterator`

**Comment by sindhura234** [comment] 2021-11-24 10:08
I just solved my above mentioned issue by just commenting `@threadsafe_generator ` in the code ..
